variables:
  - name: 'releaseVersion'
    value: '1.1.23'
  - name: 'repositoryName' # Name of the repository
    value: 'AzureAD/microsoft-authentication-library-for-objc'
  - name: 'repositoryBranch' # Name of the branch where version number will be updated for files that contain version number.
    value: 'master'
  - name: 'GithubServiceConnection' # Service connection name used to connect Github repository
    value: 'MSAL ObjC Service Connection'
  - name: 'docsRepositoryBranch' # Name of the branch where public reference docs will be pushed for github page
    value: 'gh-pages'

pr: none

resources:
  repositories:
  - repository: msalRepository
    type: github
    endpoint: 'GitHub for AzureAD and Azure-Samples (as aadidgit service)'
    name: $(repositoryName)
    ref: $(repositoryBranch)

jobs:
- job: BuildXcFrameworks
  displayName: Build MSAL framework and release
  pool:
    vmImage: 'macOS-latest'
    timeOutInMinutes: 20

  steps:
  - checkout: msalRepository
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: false
  
  - task: Bash@3
    displayName: Build MSAL docs via Jazzy
    inputs:
      filePath: 'build_docs.sh'
  - task: InstallSSHKey@0
    displayName: Install SSH Key for MSAL Github Repo
    inputs:
      knownHostsEntry: '$(sshKnownHosts)'
      sshPublicKey: '$(sshPublicKey)'
      sshKeySecureFile: 'msal_objc_private_key'
      addEntryToConfig: true
      configHostAlias: 'ADO Release Pipeline Public Key'
      configHostname: 'github.com'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        if [ ! -d "docs.temp" ]; then
            echo "Docs were not generated in previous step!"
        else
            ssh-keyscan github.com | tee -a ~/.ssh/known_hosts
            git remote set-url origin git@github.com:$(repositoryName).git

            authorName=$(git log -1 --pretty=format:'%an')
            authorEmail=$(git log -1 --pretty=format:'%ae')
            git config --global user.email "${authorEmail}"
            git config --global user.name "${authorName}"

            author=$(git log -1 --pretty=format:'%an <%ae>')
            # Create a temp branch to cherry pick doc changes
            git checkout -b 'update-docs-for-release-$(releaseVersion)'
            git add docs.temp/docs/*
            git commit -m 'adding docs for release' --author="${author}" --status
            
            # Cleanup
            rm -rf docs.temp
            git fetch origin $(docsRepositoryBranch)
            git checkout FETCH_HEAD
            git checkout $(docsRepositoryBranch)
            git clean -fd
            
            # Get previously commited changes for docs
            git cherry-pick --strategy-option theirs "update-docs-for-release-$(releaseVersion)"
            
            # Copy files in docs.temp folder to root
            \cp -r docs.temp/docs/* .
        
            # Push changes to docsRepositoryBranch branch
            git add -A
            git commit -m 'Update docs for release $(releaseVersion)' --status  --author="${author}"
            git push origin $(docsRepositoryBranch)
        fi
      workingDirectory: '$(Build.SourcesDirectory)'
      failOnStderr: false
      noProfile: false
      noRc: false
