trigger:
  branches:
    include:
    - main
  paths:
    include:
    - CHANGELOG.md

pr: none

jobs:
- job:
  displayName: "Trigger MSAL Release - OneBranch Pipeline"
  steps:
  - bash: |
      az pipelines run --project 'IDDP' --id 2424 --branch 'main' 
    displayName: 'Trigger MSAL Release - OneBranch Pipeline'
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)