trigger:
  branches:
    include:
    - main
  paths:
    include:
    - CHANGELOG.md

pr: none

jobs:
- job: TriggerRunJob
  displayName: Echo message
  pool:
    vmImage: 'macOS-13'
    timeOutInMinutes: 20

  steps:
  - task: Bash@3
    displayName: Echo Message
    inputs:
      workingDirectory: $(Build.binariesDirectory)
      targetType: 'inline'
      script: |
        echo "Ran trigger"