trigger:
  branches:
    include:
    - main
  paths:
    include:
    - CHANGELOG.md

pr: none

jobs:
- job:
  displayName: "Trigger MSAL Release - OneBranch Pipeline"
  steps:
  - bash: |
      az pipelines run --project $(ADOPROJECT) --id $(MSAL_RELEASE_ONEBRANCH_PIPELINEID) --branch 'main' --organization $(ADOORGANIZATION)
    displayName: 'Trigger MSAL Release - OneBranch Pipeline'
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)