variables:
  - name: 'releaseVersion'
    value: null
  - name: 'commonCoreReleaseVersion'
    value: null
  - name: 'frameworkChecksum'
    value: null
  - name: 'repositoryName' # Name of the repository
    value: 'AzureAD/microsoft-authentication-library-for-objc'
  - name: 'repositoryBranch' # Name of the branch where version number will be updated for files that contain version number.
    value: 'master'
  - name: 'GithubServiceConnection' # Service connection name used to connect Github repository
    value: 'MSAL ObjC Service Connection'
  - name: 'docsRepositoryBranch' # Name of the branch where public reference docs will be pushed for github page
    value: 'gh-pages'

trigger:
  branches:
    include:
    - ameyapat/test-esrp-dotnet-ver

pr: none

resources:
  repositories:
  - repository: msalRepository
    type: github
    endpoint: 'GitHub for AzureAD and Azure-Samples (as aadidgit service)'
    name: $(repositoryName)
    ref: $(repositoryBranch)

jobs:
- job: BuildXcFrameworks
  displayName: Git Issue creation test
  pool:
    vmImage: 'macOS-10.15'
    timeOutInMinutes: 20

  steps:
  - checkout: msalRepository
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: false
  - task: UsePythonVersion@0
    displayName: Use Python 3.x
  - bash: python3 -m pip install github3.py==2.0.0
    displayName: Install the github3.py REST API client for Python
  - task: PythonScript@0
    displayName: Create Issue if Pipeline fails
    inputs:
      scriptSource: inline
      script: |
        import github3
        import requests
        import textwrap
        from pprint import pprint
        from subprocess import run, PIPE
        auth_header = ""
        try:
            auth_header = run(["git", "config", "http.$(Build.Repository.URI).extraheader"], text=True, check=True, stdout=PIPE).stdout.strip()
        except Exception as e:
          pprint(e)
        class HTTPHardcodedHeaderAuth(requests.auth.AuthBase):
            def __call__(self, r):
                r.headers['Authorization'] = auth_header.replace("AUTHORIZATION: ", "")
                return r

        github = github3.GitHub()
        github.session.auth = HTTPHardcodedHeaderAuth()
        github_org, repo = "$(Build.Repository.Name)".split("/")
        team = github.organization('AzureAd').team(3752064).as_json()
        pprint(team)
        github.create_issue(github_org, repo, "Title for the Issue", "Body of the issue", assignee=appleidentityteam, labels=['automation failure'])