trigger:
  branches:
    include:
    - ameyapat/spm-framework-build
  paths:
    include:
    - azure_pipelines/spm-framework.yml
    exclude:
    - azure_pipelines
    - Package.swift

variables:
  - name: 'releaseVersion'
    value: null
  - name: 'frameworkChecksum'
    value: null

jobs:
- job: BuildXcFrameworks
  pool:
    vmImage: 'macOS-latest'
    timeOutInMinutes: 20

  steps:
  - checkout: self
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: true

  - task: Shellpp@0
    inputs:
      type: 'InlineScript'
      script: 'echo $(git config -l)'