trigger:
  branches:
    include:
    - ameyapat/spm-framework-build
  paths:
    include:
    - azure_pipelines/spm-framework.yml
    exclude:
    - azure_pipelines
    - Package.swift

variables:
  - name: 'releaseVersion'
    value: null
  - name: 'frameworkChecksum'
    value: null

resources:
  repositories:
  - repository: msalRepository
    type: github
    endpoint: 'github.com_ameyapat'
    name: ameyapat/microsoft-authentication-library-for-objc
    ref: master

jobs:
- job: BuildXcFrameworks
  pool:
    vmImage: 'macOS-latest'
    timeOutInMinutes: 20

  steps:
  - checkout: msalRepository
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: true

  - task: Bash@3
    displayName: Update package.swift with url & checksum & git push 
    inputs:
      targetType: 'inline'
      script: |
        git checkout --track origin/master

        git checkout -b update-package-for-$(releaseVersion)
        perl -i -pe's/checksum:\s+\"[\da-fA-F]{64}\"/checksum: \"$(frameworkChecksum)\"/' Package.swift
        perl -i -pe's/releases\/download\/[0-9a-zA-Z\.].+\//releases\/download\/$(releaseVersion)\//' Package.swift
        git add Package.swift
        git commit -a -m "Updating MSAL framework checksum & url for $(releaseVersion) [skip ci]"
        git checkout master
        git merge update-package-for-$(releaseVersion)
        git branch -d update-package-for-$(releaseVersion)
      workingDirectory: '$(Build.SourcesDirectory)'
      failOnStderr: true
      noProfile: false
      noRc: false