trigger:
  branches:
    include:
    - ameyapat/spm-framework-build
  paths:
    include:
    - azure_pipelines/spm-framework.yml
    exclude:
    - azure_pipelines
    - Package.swift

variables:
  - name: 'releaseVersion'
    value: null
  - name: 'frameworkChecksum'
    value: null

resources:
  repositories:
  - repository: ameyapatRepo
    type: github
    endpoint: 'github.com_ameyapat'
    name: ameyapat/microsoft-authentication-library-for-objc
    ref: master

jobs:
- job: BuildXcFrameworks
  pool:
    vmImage: 'macOS-latest'
    timeOutInMinutes: 20

  steps:
  - checkout: ameyapatRepo
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: true

  - task: Shellpp@0
    inputs:
      type: 'InlineScript'
      cwd: '$(Build.SourcesDirectory)'
      failOnStandardError: true
      script: |
        perl -i -pe's/checksum/CHECKSUM/' Package.swift
        
        git status
        git commit -m "Testing commiting from pipeline [skip ci]"
        git push origin